Repository pytorch/serve, pull requests merged in 2020-07, with the labels that each got.

#489 NameError fixed in default image_classifier.py torch handler
  ts/torch_handler/image_classifier.py
Labels: bug

#452 Fix tag for latest CPU version in README
  docker/README.md
Labels: bug

#527 Updated install scripts and removed frontend build from install
  CONTRIBUTING.md
  README.md
  docs/code_coverage.md
  scripts/install_from_src
  scripts/install_from_src_macos
  scripts/install_from_src_ubuntu
  scripts/install_from_src_wsl
  scripts/install_utils
  setup.py
  torchserve_sanity.sh
Labels: enhancement

#550 Fix readme for examples/image_classifier
  examples/image_classifier/README.md
Labels: documentation

#462 Added support for model specific custom requirements.txt in mar file
  docs/configuration.md
  docs/custom_service.md
  frontend/modelarchive/src/main/java/org/pytorch/serve/archive/Manifest.java
  frontend/modelarchive/src/main/java/org/pytorch/serve/archive/ModelArchive.java
  frontend/modelarchive/src/test/java/org/pytorch/serve/archive/ModelArchiveTest.java
  frontend/modelarchive/src/test/resources/models/custom_invalid_python_dep.mar
  frontend/modelarchive/src/test/resources/models/custom_python_dep.mar
  frontend/server/src/main/java/org/pytorch/serve/ModelServer.java
  frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java
  frontend/server/src/main/java/org/pytorch/serve/metrics/MetricCollector.java
  frontend/server/src/main/java/org/pytorch/serve/snapshot/SnapshotManager.java
  frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
  frontend/server/src/main/java/org/pytorch/serve/util/messages/EnvironmentUtils.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java
  frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
  frontend/server/src/test/resources/config.properties
  model-archiver/README.md
  model-archiver/model_archiver/arg_parser.py
  model-archiver/model_archiver/manifest_components/model.py
  model-archiver/model_archiver/model_packaging.py
  model-archiver/model_archiver/model_packaging_utils.py
  model-archiver/model_archiver/tests/unit_tests/test_model_packaging.py
  model-archiver/model_archiver/tests/unit_tests/test_model_packaging_utils.py
Labels: enhancement
