Repository pytorch/serve, pull requests merged in 2020-10, with the labels that each got.

#275 Add .github/actions with npm modules
  .github/workflows/doc-automation.yml
  .gitignore
Labels: documentation

#595 fixed unbound variable issue while creating binaries from script
  binaries/conda/build_packages.sh
  binaries/pip/build_wheels.sh
Labels: bug

#747 Feature: Add prometheus and grafana for kubernetes setup
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/config.properties
  kubernetes/README.md
  kubernetes/config.properties
  kubernetes/images/grafana_datasource.png
  kubernetes/templates/torchserve.yaml
  kubernetes/values.yaml
Labels: enhancement

#724 added permission to venv path to model-server user
  docker/Dockerfile
  docker/Dockerfile.dev
Labels: bug
