Repository pytorch/serve, pull requests merged in 2021-05, with the labels that each got.

#1051 Resolving doc review comments from PR1023
  docs/images/DogCatBreed.png
  docs/images/NMTBackTranslate.png
  docs/images/NMTDualTranslate.png
  docs/workflows.md
  examples/Workflows/README.md
  examples/Workflows/densenet_image_classifier_pipeline/README.md
  examples/Workflows/densenet_image_classifier_pipeline/densenet_model/README.md
  examples/Workflows/densenet_image_classifier_pipeline/densenet_model/densenet_handler.py
  examples/Workflows/densenet_image_classifier_pipeline/densenet_model/model.py
  examples/Workflows/densenet_image_classifier_pipeline/densenet_workflow.yaml
  examples/Workflows/densenet_image_classifier_pipeline/densenet_workflow_handler.py
  examples/Workflows/densenet_image_classifier_pipeline/index_to_name.json
  examples/Workflows/densenet_image_classifier_pipeline/kitten.jpg
  examples/Workflows/dog_breed_classification/README.md
  examples/Workflows/nmt_tranformers_pipeline/README.md
Labels: documentation

#1057 Issue_1050
  ts_scripts/mar_config.json
  ts_scripts/marsgen.py
Labels: enhancement

#1048 Update mnist_handler.py
  examples/image_classifier/mnist/mnist_handler.py
Labels: close_after_merge

#1079 Add note about windows support for nmt example
  examples/nmt_transformer/README.md
Labels: documentation
