Repository pytorch/serve, pull requests merged in 2021-11, with the labels that each got.

#1252 HF example update
  examples/Huggingface_Transformers/Transformer_handler_generalized.py
  requirements/developer.txt
Labels: enhancement

#1294 check environment var TS_CONFIG_FILE
  ts/model_server.py
Labels: bug

#1261 feat: Add readme for fast transformers huggingface bert
  examples/FasterTransformer_HuggingFace_Bert/README.md
  kubernetes/examples/FasterTransformer_HuggingFace_Bert.md
Labels: documentation

#1236 Update serve/KFServing README.md
  kubernetes/kfserving/README.md
  kubernetes/kfserving/mnist_readme.md
Labels: documentation

#1167 Update README with CPU worker config
  README.md
Labels: documentation

#1265 remove mention of s3 in server.md
  docs/FAQs.md
  docs/server.md
Labels: documentation

#1307 optimize frontend build performance
  frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
  frontend/server/src/test/java/org/pytorch/serve/SnapshotTest.java
  frontend/server/src/test/java/org/pytorch/serve/WorkflowTest.java
Labels: enhancement

#1250 fix dataset name
  docs/default_handlers.md
Labels: documentation

#1287 update snapshot doc
  docs/snapshot.md
Labels: documentation

#1271 Issue 1120
  docs/configuration.md
  frontend/server/src/main/java/org/pytorch/serve/http/api/rest/InferenceRequestHandler.java
  frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
  frontend/server/src/main/java/org/pytorch/serve/util/codec/ModelRequestEncoder.java
  frontend/server/src/main/java/org/pytorch/serve/util/messages/ModelLoadModelRequest.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java
  frontend/server/src/main/java/org/pytorch/serve/workflow/api/http/WorkflowInferenceRequestHandler.java
  ts/context.py
  ts/model_loader.py
  ts/model_service_worker.py
  ts/protocol/otf_message_handler.py
  ts/service.py
  ts/tests/unit_tests/test_otf_codec_protocol.py
  ts/torch_handler/vision_handler.py
Labels: enhancement

#1291 HuggingFace Bert example - Batch inference README update
  examples/Huggingface_Transformers/README.md
  examples/Huggingface_Transformers/Seq_classification_artifacts/sample_text1.txt
  examples/Huggingface_Transformers/Seq_classification_artifacts/sample_text2.txt
  examples/Huggingface_Transformers/Seq_classification_artifacts/sample_text3.txt
Labels: documentation

#1298 Issue 1136
  docs/configuration.md
  frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
Labels: enhancement

#1311 support custom return code
  docs/custom_service.md
  frontend/archive/src/test/resources/models/pred-custom-return-code.mar
  frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
  ts/service.py
  ts/utils/util.py
Labels: enhancement

#1259 torchprep [experimental]
  experimental/torchprep/README.md
  experimental/torchprep/example.py
  experimental/torchprep/poetry.lock
  experimental/torchprep/pyproject.toml
  experimental/torchprep/tests/__init__.py
  experimental/torchprep/tests/test_torchprep.py
  experimental/torchprep/torchprep/__init__.py
  experimental/torchprep/torchprep/main.py
Labels: enhancement

#1190 KFServing v2 protocol support
  frontend/server/src/main/java/org/pytorch/serve/http/api/rest/InferenceRequestHandler.java
  frontend/server/src/main/java/org/pytorch/serve/openapi/OpenApiUtils.java
  frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
  frontend/server/src/test/resources/describe_api.json
  frontend/server/src/test/resources/inference_open_api.json
  kubernetes/kfserving/Dockerfile.dev
  kubernetes/kfserving/Huggingface_readme.md
  kubernetes/kfserving/README.md
  kubernetes/kfserving/config.properties
  kubernetes/kfserving/handler/v2/README.md
  kubernetes/kfserving/handler/v2/bert_handler.py
  kubernetes/kfserving/handler/v2/mnist_handler.py
  kubernetes/kfserving/image_transformer/README.md
  kubernetes/kfserving/kf_request_json/bert_v2.json
  kubernetes/kfserving/kf_request_json/mnist_v2.json
  kubernetes/kfserving/kf_request_json/v1/img2bytearray.py
  kubernetes/kfserving/kf_request_json/v2/totensor.py
  kubernetes/kfserving/kf_request_json/v2/utils.py
  kubernetes/kfserving/kfserving_wrapper/README.md
  kubernetes/kfserving/kfserving_wrapper/TSModelRepository.py
  kubernetes/kfserving/kfserving_wrapper/TorchserveModel.py
  kubernetes/kfserving/kfserving_wrapper/__main__.py
  kubernetes/kfserving/mnist_readme.md
  kubernetes/kfserving/reference_yaml/torchserve-deployment/v1/ts-sample-gpu.yaml
  kubernetes/kfserving/reference_yaml/torchserve-deployment/v1/ts_sample-gs.yaml
  kubernetes/kfserving/reference_yaml/torchserve-deployment/v1/ts_sample.yaml
  kubernetes/kfserving/reference_yaml/torchserve-deployment/v2/ts-sample-gpu.yaml
  kubernetes/kfserving/reference_yaml/torchserve-deployment/v2/ts_sample-gs.yaml
  kubernetes/kfserving/reference_yaml/torchserve-deployment/v2/ts_sample.yaml
  kubernetes/kfserving/text_classifier_readme.md
  plugins/DDBEndPoint/src/main/resources/META-INF/services/org.pytorch.serve.servingsdk.snapshot.SnapshotSerializer
  setup.py
  test/README.md
  test/postman/kfv2_api_test_collection.json
  test/postman/kfv2_https_test_collection.json
  test/postman/kfv2_inference_data.json
  test/regression_tests.py
  test/resources/config_kfv2.properties
  ts/torch_handler/request_envelope/kfservingv2.py
  ts_scripts/api_utils.py
  ts_scripts/install_dependencies.py
  ts_scripts/torchserve_grpc_client.py
Labels: enhancement
