Repository pytorch/serve, pull requests merged in 2022-08, with the labels that each got.

#1774 Fix #1740: Handle OPTIONS in management API
  frontend/server/src/main/java/org/pytorch/serve/http/api/rest/ManagementRequestHandler.java
  frontend/server/src/main/java/org/pytorch/serve/openapi/OpenApiUtils.java
  frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
  frontend/server/src/test/java/org/pytorch/serve/TestUtils.java
  frontend/server/src/test/resources/model_management_api.json
Labels: bug

#1767 upgrade PT to 1.12
  CONTRIBUTING.md
  docker/README.md
  docker/build_image.sh
  docs/code_coverage.md
  docs/getting_started.md
  requirements/torch_cu102_linux.txt
  requirements/torch_cu113_linux.txt
  requirements/torch_cu113_windows.txt
  requirements/torch_cu116_linux.txt
  requirements/torch_cu116_windows.txt
  requirements/torch_darwin.txt
  requirements/torch_linux.txt
  requirements/torch_windows.txt
  test/pytest/conftest.py
  test/pytest/test_example_scriptable_tokenzier.py
  ts_scripts/install_dependencies.py
Labels: enhancement, p0

#1658 deprecate ci benchmark dir
  ci/benchmark/buildspec.yml
Labels: benchmark, p2

#1709 Fixed broken path joins and unclosed files
  benchmarks/auto_benchmark.py
  benchmarks/benchmark-ab.py
  benchmarks/utils/gen_md_report.py
  examples/dcgan_fashiongen/dcgan_fashiongen_handler.py
  examples/text_to_speech_synthesizer/create_mar.py
  test/pytest/test_gRPC_inference_api.py
  test/pytest/test_gRPC_management_apis.py
  test/pytest/test_handler.py
  test/pytest/test_metrics.py
  test/pytest/test_metrics_kf.py
  test/pytest/test_model_archiver.py
  test/pytest/test_pytorch_profiler.py
  test/pytest/test_snapshot.py
  test/pytest/test_utils.py
  ts/model_loader.py
  ts/model_server.py
  ts_scripts/print_env_info.py
Labels: windows, p1

#1739 Automate Release: From scratch builds
  .github/workflows/official_release.yml
  binaries/build.py
  binaries/conda/build_packages.py
  binaries/pip/README.md
  binaries/pip/build_wheels.sh
  binaries/pip/retag_pypi_binary.sh
  binaries/upload.py
  docker/build_upload_release.py
  docker/docker_nightly.py
  kubernetes/kserve/build_upload_release.py
  ts_scripts/utils.py
Labels: ci
