Repository pytorch/serve, pull requests merged in 2022-09, with the labels that each got.

#1393 FAQ update: international language decode
  docs/FAQs.md
Labels: documentation

#1854 fix workerthread hang due to grpc client cancel connection
  frontend/server/src/main/java/org/pytorch/serve/grpcimpl/InferenceImpl.java
  frontend/server/src/main/java/org/pytorch/serve/grpcimpl/ManagementImpl.java
Labels: bug, p0

#1817 CPP OTFProtocol implementation for inference request and response
  cpp/CMakeLists.txt
  cpp/build.sh
  cpp/src/backends/CMakeLists.txt
  cpp/src/backends/process/model_worker.cc
  cpp/src/backends/process/model_worker.hh
  cpp/src/backends/process/model_worker_socket.cc
  cpp/src/backends/protocol/isocket.hh
  cpp/src/backends/protocol/otf_message.cc
  cpp/src/backends/protocol/otf_message.hh
  cpp/src/backends/protocol/socket.cc
  cpp/src/backends/protocol/socket.hh
  cpp/src/backends/torch_scripted/handler/base_handler.cc
  cpp/src/backends/torch_scripted/handler/base_handler.hh
  cpp/src/backends/torch_scripted/torch_scripted_backend.cc
  cpp/src/backends/torch_scripted/torch_scripted_backend.hh
  cpp/src/resources/logging.config
  cpp/src/utils/CMakeLists.txt
  cpp/src/utils/logging.cc
  cpp/src/utils/logging.hh
  cpp/src/utils/message.hh
  cpp/src/utils/model_archive.cc
  cpp/src/utils/model_archive.hh
  cpp/test/CMakeLists.txt
  cpp/test/backends/otf_protocol_and_handler_test.cc
  cpp/test/backends/protocol/mock_socket.hh
  cpp/test/backends/protocol/otf_message_test.cc
  cpp/test/resources/logging/invalid.config
  cpp/test/resources/logging/log_json.config
  cpp/test/resources/logging/log_to_file.config
  cpp/test/utils/logging_test.cc
Labels: c++

#1866 Validate torchserve process in pid file before starting
  ts/model_server.py
Labels: bug, triaged

#1882 fix pynvml import failure
  ts/metrics/system_metrics.py
Labels: bug, benchmark, p0

#1856 Added dev mode to `install_from_src.py`
  CONTRIBUTING.md
  ts_scripts/install_from_src.py
  ts_scripts/utils.py
Labels: usability

#1802 Util fixes
  ts/utils/util.py
Labels: triaged, code-quality
