Repository pytorch/serve, pull requests merged in 2022-03, with the labels that each got.

#1497 add dog breed, mmf and bert in model zoo
  benchmarks/benchmark-ab.py
  docs/model_zoo.md
Labels: documentation

#1508 fix failed to create model archive
  frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelArchive.java
  frontend/archive/src/test/java/org/pytorch/serve/archive/model/ModelArchiveTest.java
  frontend/archive/src/test/resources/models/noop_no_archive_no_version/noop/MAR-INF/MANIFEST.json
  frontend/archive/src/test/resources/models/noop_no_archive_no_version/noop/model.pt
  frontend/archive/src/test/resources/models/noop_no_archive_no_version/noop/service.py
  frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java
  frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
Labels: bug

#1509 Add common/requirements.txt to GPU docker image
  docker/Dockerfile
Labels: docker

#1491 metric json and qlog formt log for log4j2
  docs/metrics.md
  frontend/server/src/main/java/org/pytorch/serve/util/logging/JSONPatternLayout.java
  frontend/server/src/main/java/org/pytorch/serve/util/logging/QLogLayout.java
  frontend/server/src/test/resources/log4j2-json.xml
  frontend/server/src/test/resources/log4j2-qlog.xml
Labels: bug
