Repository pytorch/serve, pull requests merged in 2022-12, with the labels that each got.

#2015 fix reponse timeout unit
  docs/configuration.md
Labels: documentation

#1960 `torch.compile()` support
  examples/image_classifier/compile.json
  examples/pt2/README.md
  ts/torch_handler/base_handler.py
  ts/utils/util.py
  ts_scripts/install_dependencies.py
  ts_scripts/spellcheck_conf/wordlist.txt
Labels: enhancement, perf, p0

#1858 mypy type annotations
  .github/workflows/lint.yml
  mypy.ini
  requirements/developer.txt
  ts/context.py
Labels: code-quality

#2017 update FAQ about config.property, model_store, load_models, models
  docs/FAQs.md
  docs/server.md
Labels: documentation
