Repository pytorch/serve, pull requests merged in 2022-07, with the labels that each got.

#1718 fix: pytorch.org/serve encrypted model serving link
  docs/README.md
Labels: documentation

#1719 Move milliseconds from batch_size to batch_delay
  docs/batch_inference_with_ts.md
Labels: documentation

#1685 Workflow for pushing conda nightly binaries and merging all nightly runs to a single workflow
  .github/workflows/torch-model-archiver-nightly-build.yml
  .github/workflows/torch-workflow-archiver-nightly-build.yml
  .github/workflows/torchserve-nightly-build.yml
  README.md
  binaries/README.md
  binaries/build.py
  binaries/conda/build_packages.py
  binaries/upload.py
  requirements/developer.txt
Labels: enhancement, p1

#1745 Don't install IPEX on Mac to unblock CI
  requirements/developer.txt
Labels: bug, dependencies, ci

#1665 Added `code-coverage.yml` using `codecov`
  .github/workflows/ci_cpu.yml
  .github/workflows/ci_gpu.yml
  codecov.yml
  ts_scripts/backend_utils.py
  ts_scripts/install_utils
  ts_scripts/modelarchiver_utils.py
  ts_scripts/workflow_archiver_utils.py
Labels: p0

#1746 Skip Flaky Java Windows Tests
  frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
  frontend/server/src/test/java/org/pytorch/serve/WorkflowTest.java
Labels: bug, windows
