Repository pytorch/serve, pull requests merged in 2023-01, with the labels that each got.

#2078 Upgrade to PyTorch 1.13.1
  requirements/torch_cu116_linux.txt
  requirements/torch_cu116_windows.txt
  requirements/torch_cu117_linux.txt
  requirements/torch_cu117_windows.txt
  requirements/torch_darwin.txt
  requirements/torch_linux.txt
  requirements/torch_windows.txt
Labels: security

#2065 [Snyk] Security upgrade ubuntu from 20.04 to rolling
  docker/Dockerfile.dev
Labels: security

#2064 [Snyk] Security upgrade ubuntu from 20.04 to rolling
  docker/Dockerfile
Labels: security

#2066 [Snyk] Security upgrade ubuntu from 20.04 to rolling
  docker/Dockerfile.neuron.dev
Labels: security

#2072 Disable Alert on Nightly GPU
  .github/workflows/benchmark_nightly_gpu.yml
Labels: easy

#2076 Update Dockerfile.dev to install gnupg before calling apt-key del 7fa2af80 (fix: #2075)
  kubernetes/kserve/Dockerfile.dev
Labels: easy

#2081 Update to safe snakeyaml, grpc and gradle
  frontend/gradle.properties
  frontend/gradle/wrapper/gradle-wrapper.properties
Labels: security

#1873 Added retry action for CI
  .github/workflows/ci_cpu.yml
  .github/workflows/ci_gpu.yml
Labels: p0, ci

#2080 update runner label in regression_tests_gpu.yml
  .github/workflows/regression_tests_gpu.yml
Labels: ci

#2092 add OMP_NUMNER_THREADS in cpu benchmark; increase request to get gpu …
  .github/workflows/benchmark_nightly_cpu.yml
  benchmarks/models_config/bert_multi_gpu.yaml
  benchmarks/models_config/bert_multi_gpu_better_transformer.yaml
  benchmarks/models_config/bert_multi_gpu_no_better_transformer.yaml
  benchmarks/models_config/mnist.yaml
  benchmarks/models_config/wf_dog_breed.yaml
  benchmarks/models_config/wf_nmt_dualtranslation.yaml
Labels: benchmark
