Repository pytorch/serve, pull requests merged in 2023-04, with the labels that each got.

#2214 TorchServe decompress tgz format model
  frontend/archive/build.gradle
  frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelArchive.java
  frontend/archive/src/main/java/org/pytorch/serve/archive/utils/ZipUtils.java
  frontend/archive/src/main/java/org/pytorch/serve/archive/workflow/WorkflowArchive.java
  frontend/archive/src/test/java/org/pytorch/serve/archive/model/ModelArchiveTest.java
  frontend/archive/src/test/resources/models/noop.tar.gz
  frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java
Labels: enhancement

#2244 move misplaced config-file arg from torchserve to torch-model-archiver
  examples/pt2/README.md
Labels: easy

#2245 Revert "[easy] lint fix broken windows conda link"
  docs/torchserve_on_win_native.md
Labels: easy

#2241 Make pre-commit usage clearer in error message
  .github/workflows/lint.yml
Labels: easy

#2243 Updates to TorchServe page on pytorch.org
  README.md
  docs/index.md
Labels: easy

#2250 Fix torch.compile mac regression test
  test/pytest/test_torch_compile.py
Labels: easy

#2233 http stream response via http 1.1 chunked encoding
  docs/inference_api.md
  frontend/server/src/main/java/org/pytorch/serve/job/GRPCJob.java
  frontend/server/src/main/java/org/pytorch/serve/job/RestJob.java
  frontend/server/src/main/java/org/pytorch/serve/util/NettyUtils.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/BatchAggregator.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java
  test/pytest/test_handler.py
  ts/protocol/otf_message_handler.py
Labels: enhancement

#2257 Increase collection of benchmark artifacts to 30 for better averaging
  benchmarks/utils/report.py
  benchmarks/utils/update_artifacts.py
  benchmarks/validate_report.py
Labels: easy

#2218 deepspeed base handler and example
  docs/large_model_inference.md
  examples/large_models/deepspeed/opt/Download_models.py
  examples/large_models/deepspeed/opt/Readme.md
  examples/large_models/deepspeed/opt/custom_handler.py
  examples/large_models/deepspeed/opt/ds-config.json
  examples/large_models/deepspeed/opt/model-config.yaml
  examples/large_models/deepspeed/opt/requirements.txt
  examples/large_models/deepspeed/opt/sample_text.txt
  frontend/server/src/main/java/org/pytorch/serve/job/RestJob.java
  frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
  requirements/developer.txt
  test/postman/large_model_inference_data.json
  test/pytest/test_distributed_inference_handler.py
  test/resources/config.properties
  ts/handler_utils/distributed/deepspeed.py
  ts/torch_handler/distributed/base_deepspeed_handler.py
Labels: enhancement, example

#2267 support client timeout
  docs/configuration.md
  frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java
  frontend/archive/src/test/resources/models/echo-client-timeout.mar
  frontend/archive/src/test/resources/models/init-error.mar
  frontend/server/src/main/java/org/pytorch/serve/grpcimpl/InferenceImpl.java
  frontend/server/src/main/java/org/pytorch/serve/http/api/rest/InferenceRequestHandler.java
  frontend/server/src/main/java/org/pytorch/serve/util/messages/RequestInput.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/BatchAggregator.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/Model.java
  frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
Labels: enhancement

#2246 FAQ on slow model initialization
  docs/FAQs.md
Labels: easy
