Repository pytorch/serve, pull requests merged in 2024-05, with the labels that each got.

#3123 Fix grammer in security.md
  SECURITY.md
Labels: documentation

#3077 Integrate vllm with example Lora and Mistral
  examples/large_models/utils/test_llm_streaming_response.py
  examples/large_models/vllm/Readme.md
  examples/large_models/vllm/base_vllm_handler.py
  examples/large_models/vllm/config.properties
  examples/large_models/vllm/lora/Readme.md
  examples/large_models/vllm/lora/model-config.yaml
  examples/large_models/vllm/lora/prompt.json
  examples/large_models/vllm/mistral/Readme.md
  examples/large_models/vllm/mistral/custom_handler.py
  examples/large_models/vllm/mistral/model-config.yaml
  examples/large_models/vllm/mistral/prompt.json
  examples/large_models/vllm/mistral/requirements.txt
  examples/large_models/vllm/mistral/sample_text.txt
  examples/large_models/vllm/requirements.txt
  test/pytest/test_example_vllm.py
  ts_scripts/spellcheck_conf/wordlist.txt
Labels: documentation, enhancement

#3130 Resnet18 torch.compile example
  examples/image_classifier/resnet_18/README.md
Labels: example, bootcamp

#3135 Fix grammer in security.md
  SECURITY.md
Labels: documentation

#3133 Example llama3 on inf2
  examples/large_models/inferentia2/llama/Readme.md
  examples/large_models/inferentia2/llama/continuous_batching/Readme.md
  examples/large_models/inferentia2/llama/continuous_batching/base_neuronx_continuous_batching_handler.py
  examples/large_models/inferentia2/llama/continuous_batching/inf2-llama-continuous-batching.ipynb
  examples/large_models/inferentia2/llama/continuous_batching/llama2-model-config.yaml
  examples/large_models/inferentia2/llama/continuous_batching/llama3-model-config.yaml
  examples/large_models/inferentia2/llama/requirements.txt
  examples/large_models/inferentia2/llama/streamer/Readme.md
  examples/large_models/inferentia2/llama/streamer/base_neuronx_microbatching_handler.py
  examples/large_models/inferentia2/llama/streamer/inf2-llama-micro-batching.ipynb
  examples/large_models/inferentia2/llama/streamer/llama2-model-config.yaml
  examples/large_models/inferentia2/llama/streamer/llama3-model-config.yaml
  examples/large_models/inferentia2/llama2/requirements.txt
Labels: example

#3139 remove dup neuron continuous batch base handler
  ts/torch_handler/distributed/base_neuronx_continuous_batching_handler.py
Labels: bug

#3142 Sequence batch via http
  examples/stateful/Readme.md
  examples/stateful/model-config.yaml
  frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java
  frontend/server/src/main/java/org/pytorch/serve/grpcimpl/InferenceImpl.java
  frontend/server/src/main/java/org/pytorch/serve/job/Job.java
  frontend/server/src/main/java/org/pytorch/serve/job/JobGroup.java
  frontend/server/src/main/java/org/pytorch/serve/util/ApiUtils.java
  frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
  frontend/server/src/main/java/org/pytorch/serve/util/messages/RequestInput.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/BatchAggregator.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/ContinuousBatching.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/Model.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/SequenceBatchAggregator.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/WorkLoadManager.java
  frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java
  test/pytest/test_example_stateful_http.py
  ts/context.py
Labels: documentation, enhancement

#3151 GPT-FAST-MIXTRAL-MOE integration
  examples/large_models/gpt_fast_mixtral_moe/README.md
  examples/large_models/gpt_fast_mixtral_moe/model_config.yaml
  examples/large_models/gpt_fast_mixtral_moe/model_config_tp.yaml
  examples/large_models/gpt_fast_mixtral_moe/request.json
Labels: bootcamp
