Repository pytorch/serve, pull requests merged in 2024-06, with the labels that each got.

#3159 Update performance documentation
  docs/performance_checklist.md
  docs/performance_guide.md
Labels: documentation

#3200 Update image_classifier/densenet-161 to include torch.compile
  examples/image_classifier/densenet_161/README.md
  examples/image_classifier/densenet_161/model-config.yaml
Labels: bootcamp, torch.compile

#3132 Torchserve support for Intel GPUs
  examples/intel_extension_for_pytorch/README.md
  frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
  ts/torch_handler/base_handler.py
  ts_scripts/spellcheck_conf/wordlist.txt
Labels: torch.compile

#3203 TensorRT example with torch.compile
  examples/torch_tensorrt/torchcompile/README.md
  examples/torch_tensorrt/torchcompile/model-config.yaml
  examples/torch_tensorrt/torchcompile/model.py
  examples/torch_tensorrt/torchcompile/requirements.txt
  examples/torch_tensorrt/torchscript/README.md
  examples/torch_tensorrt/torchscript/requirements.txt
  examples/torch_tensorrt/torchscript/resnet_tensorrt.py
  ts/utils/util.py
  ts_scripts/spellcheck_conf/wordlist.txt
Labels: torch.compile

#3201 BERT with torch.compile
  examples/Huggingface_Transformers/Download_Transformer_models.py
  examples/Huggingface_Transformers/README.md
  examples/Huggingface_Transformers/Transformer_handler_generalized.py
  examples/Huggingface_Transformers/model-config.yaml
  examples/Huggingface_Transformers/setup_config.json
  ts_scripts/spellcheck_conf/wordlist.txt
Labels: torch.compile
